In [72]:
DATA_PATH = "C:/Users/ltk65/Downloads/scu-ai-competition-202401/"
DATA_PATH

'C:/Users/ltk65/Downloads/scu-ai-competition-202401/'

In [73]:
import pandas as pd
import numpy as np

df = pd.read_csv(f"{DATA_PATH}train.csv") # 학습데이터
df_t = pd.read_csv(f"{DATA_PATH}test.csv") # 테스트 데이터
df.shape

(4223, 18)

In [74]:
df.head(10)

,ID,나이,성별,티록신_복용_여부,항갑상선제_복용_여부,지병_여부,임신_여부,갑상선_수술_이력,I131_치료_여부,갑상선저하_인지_여부,갑상선항진증_인지_여부,리튬_치료_여부,갑상선종_여부,종양_여부,TSH,FreeT3,FreeT4,target
0,train_0,59.0,남,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,NaN,NaN,0.77,0
1,train_1,63.0,남,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,33.00,1.5,NaN,1
2,train_2,65.0,여,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,1.70,2.3,0.95,0
3,train_3,33.0,남,아니오,아니오,예,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,6.20,NaN,0.66,0
4,train_4,64.0,여,예,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,1.20,NaN,0.95,0
5,train_5,67.0,여,예,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.45,NaN,1.02,0
6,train_6,69.0,남,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,2.30,1.4,0.86,0
7,train_7,38.0,여,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.93,NaN,1.05,0
8,train_8,73.0,여,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,NaN,NaN,NaN,0
9,train_9,42.0,여,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.10,1.5,0.80,0

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4223 entries, 0 to 4222
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            4223 non-null   object
 1   나이            4220 non-null   float64
 2   성별            4086 non-null   object
 3   티록신_복용_여부     4223 non-null   object
 4   항갑상선제_복용_여부   4223 non-null   object
 5   지병_여부         4223 non-null   object
 6   임신_여부         4223 non-null   object
 7   갑상선_수술_이력     4223 non-null   object
 8   I131_치료_여부    4223 non-null   object
 9   갑상선저하_인지_여부   4223 non-null   object
 10  갑상선항진증_인지_여부  4223 non-null   object
 11  리튬_치료_여부      4223 non-null   object
 12  갑상선종_여부       4223 non-null   object
 13  종양_여부         4223 non-null   object
 14  TSH           3832 non-null   float64
 15  FreeT3        2989 non-null   float64
 16  FreeT4        3854 non-null   float64
 17  target        4223 non-null   int64
dtypes: float64(4), int64(1), object(13)
memory usage: 594.0+ KB

In [57]:
df.isnull().sum()

ID                 0
나이                 3
성별               137
티록신_복용_여부          0
항갑상선제_복용_여부        0
지병_여부              0
임신_여부              0
갑상선_수술_이력          0
I131_치료_여부         0
갑상선저하_인지_여부        0
갑상선항진증_인지_여부       0
리튬_치료_여부           0
갑상선종_여부            0
종양_여부              0
TSH              391
FreeT3          1234
FreeT4           369
target             0
dtype: int64

UNK > 여자

In [76]:
fill1 = fill_tsh = df["TSH"].mean()
fill2 = fill_free_t3 = df["FreeT3"].mean()
fill3 = fill_free_t4 = df["FreeT4"].mean()
fill4 = fill_age = df['나이'].mean()
fill1, fill2, fill3, fill4

(4.953486423277662, 2.021445298762128, 0.9651530877010898, 52.12037914691943)

In [77]:
# train
df["나이"] = df["나이"].fillna(fill4)
df["성별"] = df["성별"].fillna("여")
df["TSH"] = df["TSH"].fillna(fill_tsh)
df["FreeT3"] = df["FreeT3"].fillna(fill_free_t3)
df["FreeT4"] = df["FreeT4"].fillna(fill_free_t4)

In [78]:
# test
df_t["나이"] = df_t["나이"].fillna(fill4)
df_t["성별"] = df_t["성별"].fillna("여")
df_t["TSH"] = df_t["TSH"].fillna(fill_tsh)
df_t["FreeT3"] = df_t["FreeT3"].fillna(fill_free_t3)
df_t["FreeT4"] = df_t["FreeT4"].fillna(fill_free_t4)

In [79]:
# train
df['성별'] = df['성별'].replace('UNK', '여')
df['성별'].value_counts()

성별
여    2904
남    1319
Name: count, dtype: int64

In [80]:
# test
df_t['성별'] = df_t['성별'].replace('UNK', '여')
df_t['성별'].value_counts()

성별
여    2358
남    1098
Name: count, dtype: int64

In [81]:
train = df.iloc[:,1:-1]
target = df.iloc[:,-1]

In [113]:
test_input = df_t.iloc[:,1:]

In [114]:
train.shape, test_input.shape

((4223, 28), (3456, 16))

In [111]:
train.head()

,나이,TSH,FreeT3,FreeT4,성별_남,성별_여,티록신_복용_여부_아니오,티록신_복용_여부_예,항갑상선제_복용_여부_아니오,항갑상선제_복용_여부_예,...,갑상선저하_인지_여부_아니오,갑상선저하_인지_여부_예,갑상선항진증_인지_여부_아니오,갑상선항진증_인지_여부_예,리튬_치료_여부_아니오,리튬_치료_여부_예,갑상선종_여부_아니오,갑상선종_여부_예,종양_여부_아니오,종양_여부_예
0,0.604167,0.010484,0.109830,0.278075,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.645833,0.069905,0.080780,0.382435,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,0.666667,0.003591,0.125348,0.374332,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.333333,0.013125,0.109830,0.219251,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.656250,0.002532,0.109830,0.374332,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [115]:
test_input.head()

,나이,성별,티록신_복용_여부,항갑상선제_복용_여부,지병_여부,임신_여부,갑상선_수술_이력,I131_치료_여부,갑상선저하_인지_여부,갑상선항진증_인지_여부,리튬_치료_여부,갑상선종_여부,종양_여부,TSH,FreeT3,FreeT4
0,37.0,남,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,4.953486,2.021445,0.83
1,55.0,남,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.050000,1.500000,0.72
2,71.0,여,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.100000,1.900000,0.97
3,35.0,여,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.970000,2.021445,0.97
4,16.0,남,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,아니오,0.300000,2.021445,1.06

In [86]:
from sklearn.preprocessing import OneHotEncoder
cols = train.select_dtypes("object").columns.tolist()
enc = OneHotEncoder(handle_unknown = 'ignore')
print(cols)
print(enc)

['성별', '티록신_복용_여부', '항갑상선제_복용_여부', '지병_여부', '임신_여부', '갑상선_수술_이력', 'I131_치료_여부', '갑상선저하_인지_여부', '갑상선항진증_인지_여부', '리튬_치료_여부', '갑상선종_여부', '종양_여부']
OneHotEncoder(handle_unknown='ignore')

In [87]:
# 학습데이터
tmp = pd.DataFrame(
    enc.fit_transform(train[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
train = pd.concat([train,tmp],axis=1).drop(columns=cols) # 범주형 컬럼 제거
train.head()

,나이,TSH,FreeT3,FreeT4,성별_남,성별_여,티록신_복용_여부_아니오,티록신_복용_여부_예,항갑상선제_복용_여부_아니오,항갑상선제_복용_여부_예,...,갑상선저하_인지_여부_아니오,갑상선저하_인지_여부_예,갑상선항진증_인지_여부_아니오,갑상선항진증_인지_여부_예,리튬_치료_여부_아니오,리튬_치료_여부_예,갑상선종_여부_아니오,갑상선종_여부_예,종양_여부_아니오,종양_여부_예
0,59.0,4.953486,2.021445,0.770000,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,63.0,33.000000,1.500000,0.965153,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,65.0,1.700000,2.300000,0.950000,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,33.0,6.200000,2.021445,0.660000,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,64.0,1.200000,2.021445,0.950000,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [116]:
# 테스트데이터
tmp = pd.DataFrame(
    enc.transform(test_input[cols]).toarray(), # 테스트데이터는 transform 만 해야한다.
    columns = enc.get_feature_names_out()
)
test_input = pd.concat([test_input,tmp],axis=1).drop(columns=cols) # 범주형 컬럼 제거
test_input.head()

,나이,TSH,FreeT3,FreeT4,성별_남,성별_여,티록신_복용_여부_아니오,티록신_복용_여부_예,항갑상선제_복용_여부_아니오,항갑상선제_복용_여부_예,...,갑상선저하_인지_여부_아니오,갑상선저하_인지_여부_예,갑상선항진증_인지_여부_아니오,갑상선항진증_인지_여부_예,리튬_치료_여부_아니오,리튬_치료_여부_예,갑상선종_여부_아니오,갑상선종_여부_예,종양_여부_아니오,종양_여부_예
0,37.0,4.953486,2.021445,0.83,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,55.0,0.050000,1.500000,0.72,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,71.0,0.100000,1.900000,0.97,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,35.0,0.970000,2.021445,0.97,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,16.0,0.300000,2.021445,1.06,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [90]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [91]:
# 학습데이터
train[train.columns] = scaler.fit_transform(train)
train.head()

,나이,TSH,FreeT3,FreeT4,성별_남,성별_여,티록신_복용_여부_아니오,티록신_복용_여부_예,항갑상선제_복용_여부_아니오,항갑상선제_복용_여부_예,...,갑상선저하_인지_여부_아니오,갑상선저하_인지_여부_예,갑상선항진증_인지_여부_아니오,갑상선항진증_인지_여부_예,리튬_치료_여부_아니오,리튬_치료_여부_예,갑상선종_여부_아니오,갑상선종_여부_예,종양_여부_아니오,종양_여부_예
0,0.604167,0.010484,0.109830,0.278075,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.645833,0.069905,0.080780,0.382435,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,0.666667,0.003591,0.125348,0.374332,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.333333,0.013125,0.109830,0.219251,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.656250,0.002532,0.109830,0.374332,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [117]:
# test
test_input[test_input.columns] = scaler.transform(test_input)
test_input.head()

,나이,TSH,FreeT3,FreeT4,성별_남,성별_여,티록신_복용_여부_아니오,티록신_복용_여부_예,항갑상선제_복용_여부_아니오,항갑상선제_복용_여부_예,...,갑상선저하_인지_여부_아니오,갑상선저하_인지_여부_예,갑상선항진증_인지_여부_아니오,갑상선항진증_인지_여부_예,리튬_치료_여부_아니오,리튬_치료_여부_예,갑상선종_여부_아니오,갑상선종_여부_예,종양_여부_아니오,종양_여부_예
0,0.375000,0.010484,0.109830,0.310160,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.562500,0.000095,0.080780,0.251337,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,0.729167,0.000201,0.103064,0.385027,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.354167,0.002045,0.109830,0.385027,0.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.156250,0.000625,0.109830,0.433155,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [104]:
#from sklearn.model_selection import train_test_split
#train_input, val_input, train_target, val_target = train_test_split(train,target,test_size=0.1,random_state=42)

In [105]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
cv = KFold(n_splits=5,shuffle=True, random_state=42)

In [133]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=17)
scores = cross_val_score(model,train,target,cv = cv ,scoring='f1',n_jobs = -1)
np.mean(scores)

0.8699841158218973

In [134]:
model = RandomForestClassifier(random_state=42)
model.fit(train,target)

RandomForestClassifier(random_state=42)

In [135]:
pred = model.predict(test_input)
pred.shape

(3456,)

In [136]:
submit = pd.read_csv(f"{DATA_PATH}sample_submission.csv")
submit

             ID  target
0        test_0     NaN
1        test_1     NaN
2        test_2     NaN
3        test_3     NaN
4        test_4     NaN
...         ...     ...
3451  test_3451     NaN
3452  test_3452     NaN
3453  test_3453     NaN
3454  test_3454     NaN
3455  test_3455     NaN

[3456 rows x 2 columns]

In [137]:
submit["target"] = pred
submit

             ID  target
0        test_0       0
1        test_1       0
2        test_2       0
3        test_3       0
4        test_4       0
...         ...     ...
3451  test_3451       0
3452  test_3452       0
3453  test_3453       0
3454  test_3454       0
3455  test_3455       0

[3456 rows x 2 columns]